resilience4j.rateLimiter :
  instances :
    firstService :
      limitForPeriod : 2
      limitRefreshPeriod : 2s
      timeoutDuration : 10s
      registerHealthIndicator : true
      eventConsumerBufferSize : 100



management :
  endpoints :
    web :
      exposure :
        include : "*"
        
  endpoint :
    health :
      show-details : always
